apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: default
    isDefault: true